// Generated by https://quicktype.io

export type InputType = Inactive | Outofservice | Current
export interface Inactive {
  "TERMINAL LOCATION": string;
  "TERMINAL ID": string;
  "ATM ID": string;
  "TOTAL REMAINING CASH(DEF CURR)": number;
  "LASTTRANSTIME(TLF)": number;
  CIRCLE: string;
  LASTWITHDRAWALTIME: number;
  MODULE: string;
  CURRENTSTATUS: string;
  NETWORK: string;
  REGIONNAME: number;
  BRANCHCODE: string;
}

export interface Outofservice {
  "TERMINAL ID": string;
  "ATM ID": string;
  LOCATION: string;
  CITY: string;
  MODULE: string;
  REGIONNAME: number;
  NETWORK: string;
  CIRCLE: string;
  CARDREADERERROR: string;
  CASHHANDLERERROR: string;
  "ALL CASSETTES DOWN/FATAL": string;
  "LOCAL/COMMUNICATIONERROR": string;
  EXCLUSIVELOCALERROR: string;
  JPERROR: string;
  CASHOUTERROR: string;
  INSUPERVISORY: string;
  CLOSED: string;
  ENCRYPTORERROR: string;
  REJECTBINERROR: string;
  "ALL CASSETTES DOWN/FATAL ADMIN CASH": string;
  "RECIEPT PRINT FATAL": string;
  CASHACCEPTORFAULTS: string;
  "ALL CASSETTES FULL": string;
  "AB FULL/REJECT BIN OVERFILL": string;
  MSVENDOR: string;
  SWITCH: string;
  "ATM MAKE": string;
  "SITE TYPE": string;
  "MACHINE TYPE": string;
  CONNECTIVITY: string;
  ASSOCIATEBANK: string;
  "LAST TLF TRANS TIME": number;
  "LAST WITHDRAWAL TIME": number;
  "LAST DEPOSIT TIME": number;
  STATUS: string;
  AGE: number;
  TOTALENDCASH_DEFAULTCURRENCY: number;
}

export interface Current {
  Customer: string;
  "ATM ID": string;
  Address: string;
  City: string;
  Site: string;
  "Start Date Time": number;
  "Action Code": number;
  "Status Code": number;
  "Status Description": string;
  Comments: string;
  "Reference Number": string;
  "Ticket ID": number;
}
